### ISSUE TITLE
-ltensorflow_framework

### ISSUE THREAD

**Issue by wangjp970408** [apennisi/faster_rcnn#1]
I have met some errors...

/usr/bin/ld: 找不到 -ltensorflow_framework
collect2: error: ld returned 1 exit status

I don't know what should I do?...
Can you help me? 
Thank you!

**Comment by apennisi** [comment]
It seems you do not have tensorflow installed. Anyway, check what the output of this " python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())' " is.
